# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p7j_9tr49HM5GP75ndrWMMQJ_d9QpO8R
"""

from google.colab import files
import os

print("Lütfen bilgisayarınıza inen kaggle.json dosyasını seçin:")
uploaded = files.upload()

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

print("Veri seti indiriliyor...")
!kaggle datasets download -d masoudnickparvar/brain-tumor-mri-dataset

print("Zip dosyası çıkartılıyor, bu işlem birkaç saniye sürebilir...")
!unzip -q brain-tumor-mri-dataset.zip -d brain_tumor_dataset

print("Harika! Veri seti başarıyla Colab'e yüklendi ve klasöre çıkarıldı.")

# /* 230710030 - Muhammet ASLAN */

import os
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator

# Klasör yollarımızı belirliyoruz (İndirdiğimiz zip dosyasının içinden Training ve Testing klasörleri çıkıyor)
base_dir = '/content/brain_tumor_dataset'
train_dir = os.path.join(base_dir, 'Training')
test_dir = os.path.join(base_dir, 'Testing')

# Proje gereksinimlerine göre görüntüler 224x224 boyutuna getirilecek
IMG_WIDTH = 224
IMG_HEIGHT = 224
BATCH_SIZE = 32

# Eğitim verisi için Veri Artırma (Data Augmentation) ve Normalizasyon işlemleri
# Neden yapıyoruz?: Modelin ezberlemesini (overfitting) önlemek ve farklı açılardan/koşullardan
# gelen tümör görüntülerini tanıyabilmesini sağlamak için veriyi çeşitlendiriyoruz.
train_datagen = ImageDataGenerator(
    rescale=1./255,           # Normalizasyon: Piksel değerlerini 0-1 aralığına sıkıştırır
    rotation_range=20,        # Görüntüyü rastgele 20 derece döndürür
    width_shift_range=0.1,    # Rastgele yatay kaydırma
    height_shift_range=0.1,   # Rastgele dikey kaydırma
    horizontal_flip=True,     # Yatay eksende rastgele çevirme
    validation_split=0.2      # Eğitim verisinin %20'sini modelin kendini test etmesi için ayırıyoruz
)

# Test verisi için sadece Normalizasyon yapıyoruz

test_datagen = ImageDataGenerator(rescale=1./255)

print("Eğitim verileri hazırlanıyor...")
train_generator = train_datagen.flow_from_directory(
    train_dir,
    target_size=(IMG_WIDTH, IMG_HEIGHT),
    batch_size=BATCH_SIZE,
    class_mode='categorical', # Çok sınıflı yapı (Glioma, Meningioma, vs.)
    subset='training'
)

print("\nDoğrulama (Validation) verileri hazırlanıyor...")
validation_generator = train_datagen.flow_from_directory(
    train_dir,
    target_size=(IMG_WIDTH, IMG_HEIGHT),
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    subset='validation'
)

print("\nTest verileri hazırlanıyor...")
test_generator = test_datagen.flow_from_directory(
    test_dir,
    target_size=(IMG_WIDTH, IMG_HEIGHT),
    batch_size=BATCH_SIZE,
    class_mode='categorical'
)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout

# Sınıflandırma modelimi ardışık (Sequential) bir mimari üzerine kurdum.
model = Sequential()

# 1. Evrişim (Convolution) Bloğu - Özellik Çıkarımı (Feature Extraction)
# Görüntüdeki kenar, çizgi gibi temel özellikleri yakalamak için 32 filtreli Conv2D katmanı ekledim.
# Giriş boyutunu projenin ön işleme aşamasında belirlediğim 224x224x3 (RGB) olarak ayarladım.
model.add(Conv2D(32, (3, 3), activation='relu', input_shape=(IMG_WIDTH, IMG_HEIGHT, 3)))
# Boyut azaltarak işlem yükünü hafifletmek ve önemli özellikleri öne çıkarmak için MaxPooling uyguladım.
model.add(MaxPooling2D(pool_size=(2, 2)))

# 2. Evrişim Bloğu
# Daha karmaşık örüntüleri (tümörün dokusu, şekli) yakalamak için filtre sayısını 64'e çıkardım.
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

# 3. Evrişim Bloğu
# Daha da derin ve spesifik özellikleri öğrenmesi için 128 filtreli bir katman daha ekledim.
model.add(Conv2D(128, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

# Vektörleştirme (Flatten)
# Evrişim katmanlarından çıkan 2 boyutlu matrisleri, tam bağlantılı (Dense) katmanlara
# verebilmek için tek boyutlu bir diziye (vektöre) dönüştürdüm.
model.add(Flatten())

# Tam Bağlantılı (Fully Connected) Katmanlar
# Çıkarılan özellikleri birleştirip karar mekanizması oluşturmak için 128 nöronlu gizli bir katman ekledim.
model.add(Dense(128, activation='relu'))

# Modelin ezberlemesini (overfitting) engellemek için eğitim sırasında nöronların %50'sini rastgele kapattım (Dropout).
model.add(Dropout(0.5))

# Çıkış Katmanı
# Veri setimizde 4 sınıf (glioma, meningioma, pituitary, no_tumor) olduğu için 4 nöronlu çıkış katmanı kullandım.
# Çok sınıflı bir sınıflandırma problemi olduğu için olasılık dağılımı veren 'softmax' aktivasyonunu tercih ettim.
model.add(Dense(4, activation='softmax'))

# Modeli derleme aşaması
# Optimizasyon için genelde en iyi ve hızlı sonucu veren 'adam' optimizasyon algoritmasını seçtim.
# Kayıp fonksiyonu (loss) olarak, veri setim 4 sınıflı olduğu için 'categorical_crossentropy' kullandım.
# Başarıyı ölçmek değerlendirme metriği olarak Accuracy (doğruluk) metriğini takip edeceğim.
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# Kurduğum mimarinin katmanlarını, parametre sayılarını ve çıkış boyutlarını görmek için modelin özetini yazdırdım.
model.summary()

# Modeli eğitmeye (training) başlıyorum. Eğitim sürecindeki doğruluk (accuracy) ve kayıp (loss)
# değerlerinin adım adım değişimini sonradan inceleyebilmek için tüm süreci 'history' adlı değişkene kaydettim.
history = model.fit(
    train_generator,
    epochs=10, # Modelin tüm veri setini 10 tam tur (epoch) görerek öğrenmesini sağladım.
    validation_data=validation_generator # Modelin ezber (overfitting) yapmadığından emin olmak için her tur sonunda doğrulama verisiyle test ettim.
)

# Eğitim bittikten sonra, proje tanımında benden istenen "Değerlendirme Metrikleri" bölümünü
# tamamlamak için modelin daha önce HİÇ GÖRMEDİĞİ test verileri (test_generator) üzerinde nihai bir ölçüm yaptım.
test_loss, test_accuracy = model.evaluate(test_generator)
print(f"\nModelin Test Verisindeki Doğruluğu (Accuracy): %{test_accuracy * 100:.2f}")

# Eğittiğim bu modeli daha sonra yeniden eğitmek zorunda kalmadan
# doğrudan kullanabilmek için dosyaya kaydettim.
model.save('beyin_tumoru_modeli.h5')

import matplotlib.pyplot as plt

# Modelin eğitim sürecini analiz etmek ve 'Değerlendirme Metrikleri' şartını
# görsel olarak desteklemek için doğruluk (accuracy) ve kayıp (loss) grafiklerini çizdirdim.

plt.figure(figsize=(12, 5))

# 1. Doğruluk (Accuracy) Grafiği
# Neden yapıyoruz?: Modelin verileri doğru bilme oranının zamanla nasıl arttığını
# ve ezber (overfitting) yapıp yapmadığını görmek için.
plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Eğitim Doğruluğu', color='blue', linewidth=2)
plt.plot(history.history['val_accuracy'], label='Doğrulama Doğruluğu', color='orange', linewidth=2)
plt.title('Model Doğruluğu (Accuracy)')
plt.ylabel('Doğruluk Oranı')
plt.xlabel('Epoch (Tur Sayısı)')
plt.legend(loc='lower right')
plt.grid(True)

# 2. Kayıp (Loss) Grafiği
# Neden yapıyoruz?: Modelin yaptığı hataların (kaybın) zamanla nasıl azaldığını takip etmek için.
plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Eğitim Kaybı', color='blue', linewidth=2)
plt.plot(history.history['val_loss'], label='Doğrulama Kaybı', color='orange', linewidth=2)
plt.title('Model Kaybı (Loss)')
plt.ylabel('Hata/Kayıp Oranı')
plt.xlabel('Epoch (Tur Sayısı)')
plt.legend(loc='upper right')
plt.grid(True)

# Grafikleri ekrana yazdırıyoruz
plt.tight_layout()
plt.show()

from tensorflow.keras.applications import VGG16
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, Dropout, GlobalAveragePooling2D

# Doğruluk oranını artırmak ve daha profesyonel bir özellik çıkarımı (feature extraction)
# yapmak için Transfer Learning (Transfer Öğrenme) yöntemini tercih ettim.
# Daha önceden milyonlarca görüntüyle eğitilmiş olan güçlü VGG16 mimarisini temel aldım.
# include_top=False diyerek modelin orijinal sınıflandırma kısmını attım, sadece özellik çıkarma kısmını aldım.
base_model = VGG16(weights='imagenet', include_top=False, input_shape=(IMG_WIDTH, IMG_HEIGHT, 3))

# VGG16'nın önceden öğrenmiş olduğu mükemmel özellikleri bozmamak için
# temel katmanların ağırlıklarını dondurdum (eğitilmesini engelledim).
for layer in base_model.layers:
    layer.trainable = False

# VGG16'dan çıkan özellikleri kendi sınıflandırma yapıma bağlamak için yeni katmanlar ekledim.
x = base_model.output
# Flatten yerine daha modern ve performansı artıran GlobalAveragePooling2D kullandım.
x = GlobalAveragePooling2D()(x)
# Modeli kendi verime adapte etmek için 256 nöronlu güçlü bir tam bağlantılı katman (Dense) ekledim.
x = Dense(256, activation='relu')(x)
# Aşırı öğrenmeyi (overfitting) engellemek için %50'lik bir Dropout uyguladım.
x = Dropout(0.5)(x)

# Proje gereksinimi olan 4 sınıflı (Glioma, Meningioma, Pituitary tumor, Sağlıklı) yapı için çıkış katmanı.
predictions = Dense(4, activation='softmax')(x)

# VGG16'nın temeli ile kendi eklediğim sınıflandırma başlığını birleştirerek nihai modelimi oluşturdum.
advanced_model = Model(inputs=base_model.input, outputs=predictions)

# Yeni modelimi derliyorum
advanced_model.compile(optimizer='adam',
                       loss='categorical_crossentropy',
                       metrics=['accuracy'])

print("Transfer Learning (VGG16) ile yeni modelin eğitimi başlıyor...")

# Gelişmiş modelimi eğitiyorum. Sadece eklediğim son katmanlar eğitildiği için süreç oldukça hızlı ilerleyecektir.
advanced_history = advanced_model.fit(
    train_generator,
    epochs=10,
    validation_data=validation_generator
)

# Yeni modelin daha önce HİÇ GÖRMEDİĞİ test verisindeki başarısını ölçüyorum
advanced_test_loss, advanced_test_accuracy = advanced_model.evaluate(test_generator)
print(f"\nTransfer Learning Sonrası Yeni Test Doğruluğu: %{advanced_test_accuracy * 100:.2f}")

# Yüksek doğruluk oranına sahip bu yeni modeli kaydediyorum.
advanced_model.save('gelismis_beyin_tumoru_modeli.h5')

import numpy as np
from tensorflow.keras.preprocessing import image
from tensorflow.keras.models import load_model

# 1. Az önce eğittiğimiz ve kaydettiğimiz modeli yüklüyoruz
model = load_model('gelismis_beyin_tumoru_modeli.h5')

# 2. Sınıf isimlerimizi alfabetik olarak tanımlıyoruz (Kaggle veri setindeki klasör sırasına göre)
class_names = ['glioma', 'meningioma', 'no_tumor', 'pituitary']

def tumor_tahmini_yap(resim_yolu):
    # Görüntüyü modelin beklediği 224x224 boyutunda yüklüyoruz
    img = image.load_img(resim_yolu, target_size=(224, 224))

    # Görüntüyü matematiksel bir diziye (array) çevirip normalizasyon yapıyoruz
    img_array = image.img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0) # Model resimleri "paket" halinde beklediği için boyut ekliyoruz
    img_array /= 255.0 # Piksel değerlerini 0-1 arasına çekiyoruz

    # 3. Model tahmini yapıyor
    tahminler = model.predict(img_array, verbose=0)

    # Çıkan 4 farklı olasılıktan en yüksek olanı buluyoruz
    en_yuksek_ihtimal_indeksi = np.argmax(tahminler[0])
    tahmin_edilen_sinif = class_names[en_yuksek_ihtimal_indeksi]
    guven_orani = tahminler[0][en_yuksek_ihtimal_indeksi] * 100

    # Sonucu ekrana temiz bir şekilde yazdırıyoruz
    print("\n--- SİSTEM TAHMİN SONUCU ---")
    if tahmin_edilen_sinif == 'no_tumor':
        print(f"Bulgu: %{guven_orani:.2f} güven oranıyla TÜMÖR YOK (Sağlıklı).")
    else:
        print(f"Bulgu: %{guven_orani:.2f} güven oranıyla TÜMÖR TESPİT EDİLDİ.")
        print(f"Tümör Türü: {tahmin_edilen_sinif.capitalize()}")

# Test klasörünün içinden rastgele bir Glioma tümörü resmi seçip sisteme veriyoruz:
ornek_resim_yolu = '/content/brain_tumor_dataset/Testing/glioma/Te-gl_0010.jpg'
tumor_tahmini_yap(ornek_resim_yolu)

from tensorflow.keras.applications import VGG16
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, Dropout, GlobalAveragePooling2D

# Doğruluk oranını artırmak ve daha profesyonel bir özellik çıkarımı (feature extraction)
# yapmak için Transfer Learning (Transfer Öğrenme) yöntemini tercih ettim.
# Daha önceden milyonlarca görüntüyle eğitilmiş olan güçlü VGG16 mimarisini temel aldım.
# include_top=False diyerek modelin orijinal sınıflandırma kısmını attım, sadece özellik çıkarma kısmını aldım.
base_model = VGG16(weights='imagenet', include_top=False, input_shape=(IMG_WIDTH, IMG_HEIGHT, 3))

# VGG16'nın önceden öğrenmiş olduğu mükemmel özellikleri bozmamak için
# temel katmanların ağırlıklarını dondurdum (eğitilmesini engelledim).
for layer in base_model.layers:
    layer.trainable = False

# VGG16'dan çıkan özellikleri kendi sınıflandırma yapıma bağlamak için yeni katmanlar ekledim.
x = base_model.output
# Flatten yerine daha modern ve performansı artıran GlobalAveragePooling2D kullandım.
x = GlobalAveragePooling2D()(x)
# Modeli kendi verime adapte etmek için 256 nöronlu güçlü bir tam bağlantılı katman (Dense) ekledim.
x = Dense(256, activation='relu')(x)
# Aşırı öğrenmeyi (overfitting) engellemek için %50'lik bir Dropout uyguladım.
x = Dropout(0.5)(x)

# Proje gereksinimi olan 4 sınıflı (Glioma, Meningioma, Pituitary tumor, Sağlıklı) yapı için çıkış katmanı.
predictions = Dense(4, activation='softmax')(x)

# VGG16'nın temeli ile kendi eklediğim sınıflandırma başlığını birleştirerek nihai modelimi oluşturdum.
advanced_model = Model(inputs=base_model.input, outputs=predictions)

# Yeni modelimi derliyorum
advanced_model.compile(optimizer='adam',
                       loss='categorical_crossentropy',
                       metrics=['accuracy'])

print("Transfer Learning (VGG16) ile yeni modelin eğitimi başlıyor...")

# Gelişmiş modelimi eğitiyorum. Sadece eklediğim son katmanlar eğitildiği için süreç oldukça hızlı ilerleyecektir.
advanced_history = advanced_model.fit(
    train_generator,
    epochs=10,
    validation_data=validation_generator
)

# Yeni modelin daha önce HİÇ GÖRMEDİĞİ test verisindeki başarısını ölçüyorum
advanced_test_loss, advanced_test_accuracy = advanced_model.evaluate(test_generator)
print(f"\nTransfer Learning Sonrası Yeni Test Doğruluğu: %{advanced_test_accuracy * 100:.2f}")

# Yüksek doğruluk oranına sahip bu yeni modeli kaydediyorum.
advanced_model.save('gelismis_beyin_tumoru_modeli.h5')

import numpy as np
from tensorflow.keras.preprocessing import image

# Sınıf isimlerimizi alfabetik olarak tanımlıyoruz (Kaggle veri setindeki klasör sırasına göre)
class_names = ['glioma', 'meningioma', 'no_tumor', 'pituitary']

def tumor_tahmini_yap(resim_yolu):
    try:
        # Görüntüyü modelin beklediği 224x224 boyutunda yüklüyoruz
        img = image.load_img(resim_yolu, target_size=(224, 224))
    except FileNotFoundError:
        print(f"HATA: '{resim_yolu}' yolunda resim bulunamadı.")
        print("Lütfen sol taraftaki dosya yöneticisinden Testing klasörüne girip bir resmin yolunu kopyalayarak 'ornek_resim_yolu' değişkenini güncelle.")
        return

    # Görüntüyü matematiksel bir diziye (array) çevirip normalizasyon yapıyoruz
    img_array = image.img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0) # Model resimleri "paket" halinde beklediği için boyut ekliyoruz
    img_array /= 255.0 # Piksel değerlerini 0-1 arasına çekiyoruz

    # Model tahmini yapıyor (hafızadaki 'model' değişkenini DOĞRUDAN kullanıyoruz)
    tahminler = model.predict(img_array, verbose=0)

    # Çıkan 4 farklı olasılıktan en yüksek olanı buluyoruz
    en_yuksek_ihtimal_indeksi = np.argmax(tahminler[0])
    tahmin_edilen_sinif = class_names[en_yuksek_ihtimal_indeksi]
    guven_orani = tahminler[0][en_yuksek_ihtimal_indeksi] * 100

    # Sonucu ekrana temiz bir şekilde yazdırıyoruz
    print("\n--- SİSTEM TAHMİN SONUCU ---")
    if tahmin_edilen_sinif == 'no_tumor':
        print(f"Bulgu: %{guven_orani:.2f} güven oranıyla TÜMÖR YOK (Sağlıklı).")
    else:
        print(f"Bulgu: %{guven_orani:.2f} güven oranıyla TÜMÖR TESPİT EDİLDİ.")
        print(f"Tümör Türü: {tahmin_edilen_sinif.capitalize()}")

# Test klasörünün içinden rastgele bir Glioma tümörü resmi seçip sisteme veriyoruz:
ornek_resim_yolu = '/content/brain_tumor_dataset/Testing/glioma/Te-gl_0010.jpg'
tumor_tahmini_yap(ornek_resim_yolu)

from google.colab import files
import os

print("Lütfen bilgisayarınıza inen kaggle.json dosyasını seçin:")
uploaded = files.upload()

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

print("Veri seti indiriliyor...")
!kaggle datasets download -d masoudnickparvar/brain-tumor-mri-dataset

print("Zip dosyası çıkartılıyor, bu işlem birkaç saniye sürebilir...")
!unzip -q brain-tumor-mri-dataset.zip -d brain_tumor_dataset

print("Harika! Veri seti başarıyla Colab'e yüklendi ve klasöre çıkarıldı.")

import numpy as np
from tensorflow.keras.preprocessing import image
from tensorflow.keras.models import load_model
import os

# 1. Az önce eğittiğimiz ve kaydettiğimiz modeli yüklüyoruz
model_filename = 'gelismis_beyin_tumoru_modeli.h5'

if not os.path.exists(model_filename):
    print(f"HATA: Model dosyası '{model_filename}' bulunamadı.\nLütfen '2fH_dWXbfRZD' ID'li hücreyi (Transfer Learning ile model eğitim hücresi) çalıştırarak modeli yeniden eğitin ve kaydedin.")
else:
    model = load_model(model_filename)

    # Sınıf isimlerimizi alfabetik olarak tanımlıyoruz (Kaggle veri setindeki klasör sırasına göre)
    class_names = ['glioma', 'meningioma', 'no_tumor', 'pituitary']

    def tumor_tahmini_yap(resim_yolu):
        try:
            # Görüntüyü modelin beklediği 224x224 boyutunda yüklüyoruz
            img = image.load_img(resim_yolu, target_size=(224, 224))
        except FileNotFoundError:
            print(f"HATA: '{resim_yolu}' yolunda resim bulunamadı.")
            print("Lütfen sol taraftaki dosya yöneticisinden Testing klasörüne girip bir resmin yolunu kopyalayarak 'ornek_resim_yolu' değişkenini güncelle.")
            return

        # Görüntüyü matematiksel bir diziye (array) çevirip normalizasyon yapıyoruz
        img_array = image.img_to_array(img)
        img_array = np.expand_dims(img_array, axis=0) # Model resimleri "paket" halinde beklediği için boyut ekliyoruz
        img_array /= 255.0 # Piksel değerlerini 0-1 arasına çekiyoruz

        # Model tahmini yapıyor (hafızadaki 'model' değişkenini DOĞRUDAN kullanıyoruz)
        tahminler = model.predict(img_array, verbose=0)

        # Çıkan 4 farklı olasılıktan en yüksek olanı buluyoruz
        en_yuksek_ihtimal_indeksi = np.argmax(tahminler[0])
        tahmin_edilen_sinif = class_names[en_yuksek_ihtimal_indeksi]
        guven_orani = tahminler[0][en_yuksek_ihtimal_indeksi] * 100

        # Sonucu ekrana temiz bir şekilde yazdırıyoruz
        print("\n--- SİSTEM TAHMİN SONUCU ---")
        if tahmin_edilen_sinif == 'no_tumor':
            print(f"Bulgu: %{guven_orani:.2f} güven oranıyla TÜMÖR YOK (Sağlıklı).")
        else:
            print(f"Bulgu: %{guven_orani:.2f} güven oranıyla TÜMÖR TESPİT EDİLDİ.")
            print(f"Tümör Türü: {tahmin_edilen_sinif.capitalize()}")

    # Test klasörünün içinden rastgele bir Glioma tümörü resmi seçip sisteme veriyoruz:
    ornek_resim_yolu = '/content/brain_tumor_dataset/Testing/glioma/Te-gl_129.jpg'
    tumor_tahmini_yap(ornek_resim_yolu)

from tensorflow.keras.applications import VGG16
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, Dropout, GlobalAveragePooling2D

# Doğruluk oranını artırmak ve daha profesyonel bir özellik çıkarımı (feature extraction)
# yapmak için Transfer Learning (Transfer Öğrenme) yöntemini tercih ettim.
# Daha önceden milyonlarca görüntüyle eğitilmiş olan güçlü VGG16 mimarisini temel aldım.
# include_top=False diyerek modelin orijinal sınıflandırma kısmını attım, sadece özellik çıkarma kısmını aldım.
base_model = VGG16(weights='imagenet', include_top=False, input_shape=(IMG_WIDTH, IMG_HEIGHT, 3))

# VGG16'nın önceden öğrenmiş olduğu mükemmel özellikleri bozmamak için
# temel katmanların ağırlıklarını dondurdum (eğitilmesini engelledim).
for layer in base_model.layers:
    layer.trainable = False

# VGG16'dan çıkan özellikleri kendi sınıflandırma yapıma bağlamak için yeni katmanlar ekledim.
x = base_model.output
# Flatten yerine daha modern ve performansı artıran GlobalAveragePooling2D kullandım.
x = GlobalAveragePooling2D()(x)
# Modeli kendi verime adapte etmek için 256 nöronlu güçlü bir tam bağlantılı katman (Dense) ekledim.
x = Dense(256, activation='relu')(x)
# Aşırı öğrenmeyi (overfitting) engellemek için %50'lik bir Dropout uyguladım.
x = Dropout(0.5)(x)

# Proje gereksinimi olan 4 sınıflı (Glioma, Meningioma, Pituitary tumor, Sağlıklı) yapı için çıkış katmanı.
predictions = Dense(4, activation='softmax')(x)

# VGG16'nın temeli ile kendi eklediğim sınıflandırma başlığını birleştirerek nihai modelimi oluşturdum.
advanced_model = Model(inputs=base_model.input, outputs=predictions)

# Yeni modelimi derliyorum
advanced_model.compile(optimizer='adam',
                       loss='categorical_crossentropy',
                       metrics=['accuracy'])

print("Transfer Learning (VGG16) ile yeni modelin eğitimi başlıyor...")

# Gelişmiş modelimi eğitiyorum. Sadece eklediğim son katmanlar eğitildiği için süreç oldukça hızlı ilerleyecektir.
advanced_history = advanced_model.fit(
    train_generator,
    epochs=10,
    validation_data=validation_generator
)

# Yeni modelin daha önce HİÇ GÖRMEDİĞİ test verisindeki başarısını ölçüyorum
advanced_test_loss, advanced_test_accuracy = advanced_model.evaluate(test_generator)
print(f"\nTransfer Learning Sonrası Yeni Test Doğruluğu: %{advanced_test_accuracy * 100:.2f}")

# Yüksek doğruluk oranına sahip bu yeni modeli kaydediyorum.
advanced_model.save('gelismis_beyin_tumoru_modeli.h5')

import os
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import VGG16
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, Dropout, GlobalAveragePooling2D

# 1. EKSİK OLAN DEĞİŞKENLERİ VE VERİ YÜKLEYİCİLERİ TANIMLIYORUZ (Hatanın Çözümü)
IMG_WIDTH = 224
IMG_HEIGHT = 224
BATCH_SIZE = 32

base_dir = '/content/brain_tumor_dataset'
train_dir = os.path.join(base_dir, 'Training')
test_dir = os.path.join(base_dir, 'Testing')

# Veri Artırma ve Normalizasyon
train_datagen = ImageDataGenerator(
    rescale=1./255, rotation_range=20, width_shift_range=0.1,
    height_shift_range=0.1, horizontal_flip=True, validation_split=0.2
)
test_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(
    train_dir, target_size=(IMG_WIDTH, IMG_HEIGHT), batch_size=BATCH_SIZE,
    class_mode='categorical', subset='training'
)
validation_generator = train_datagen.flow_from_directory(
    train_dir, target_size=(IMG_WIDTH, IMG_HEIGHT), batch_size=BATCH_SIZE,
    class_mode='categorical', subset='validation'
)
test_generator = test_datagen.flow_from_directory(
    test_dir, target_size=(IMG_WIDTH, IMG_HEIGHT), batch_size=BATCH_SIZE,
    class_mode='categorical', shuffle=False
)

# 2. MODELİ KURUYORUZ
base_model = VGG16(weights='imagenet', include_top=False, input_shape=(IMG_WIDTH, IMG_HEIGHT, 3))
for layer in base_model.layers:
    layer.trainable = False

x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dense(256, activation='relu')(x)
x = Dropout(0.5)(x)
predictions = Dense(4, activation='softmax')(x)

advanced_model = Model(inputs=base_model.input, outputs=predictions)
advanced_model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# 3. EĞİTİMİ BAŞLATIYOR VE KAYDEDİYORUZ
print("Eğitim başlıyor, lütfen bitene kadar bekleyin...")
advanced_history = advanced_model.fit(train_generator, epochs=10, validation_data=validation_generator)

print("Eğitim tamamlandı! Model dosyaya kaydediliyor...")
advanced_model.save('gelismis_beyin_tumoru_modeli.h5')
print("Model başarıyla kaydedildi! Artık tahmin (test) kodunu çalıştırabilirsin.")

import numpy as np
from tensorflow.keras.preprocessing import image
from tensorflow.keras.models import load_model
import os

# 1. Az önce eğittiğimiz ve kaydettiğimiz modeli yüklüyoruz
model_filename = 'gelismis_beyin_tumoru_modeli.h5'

if not os.path.exists(model_filename):
    print(f"HATA: Model dosyası '{model_filename}' bulunamadı.\nLütfen '2fH_dWXbfRZD' ID'li hücreyi (Transfer Learning ile model eğitim hücresi) çalıştırarak modeli yeniden eğitin ve kaydedin.")
else:
    model = load_model(model_filename)

    # Sınıf isimlerimizi alfabetik olarak tanımlıyoruz (Kaggle veri setindeki klasör sırasına göre)
    class_names = ['glioma', 'meningioma', 'no_tumor', 'pituitary']

    def tumor_tahmini_yap(resim_yolu):
        try:
            # Görüntüyü modelin beklediği 224x224 boyutunda yüklüyoruz
            img = image.load_img(resim_yolu, target_size=(224, 224))
        except FileNotFoundError:
            print(f"HATA: '{resim_yolu}' yolunda resim bulunamadı.")
            print("Lütfen sol taraftaki dosya yöneticisinden Testing klasörüne girip bir resmin yolunu kopyalayarak 'ornek_resim_yolu' değişkenini güncelle.")
            return

        # Görüntüyü matematiksel bir diziye (array) çevirip normalizasyon yapıyoruz
        img_array = image.img_to_array(img)
        img_array = np.expand_dims(img_array, axis=0) # Model resimleri "paket" halinde beklediği için boyut ekliyoruz
        img_array /= 255.0 # Piksel değerlerini 0-1 arasına çekiyoruz

        # Model tahmini yapıyor (hafızadaki 'model' değişkenini DOĞRUDAN kullanıyoruz)
        tahminler = model.predict(img_array, verbose=0)

        # Çıkan 4 farklı olasılıktan en yüksek olanı buluyoruz
        en_yuksek_ihtimal_indeksi = np.argmax(tahminler[0])
        tahmin_edilen_sinif = class_names[en_yuksek_ihtimal_indeksi]
        guven_orani = tahminler[0][en_yuksek_ihtimal_indeksi] * 100

        # Sonucu ekrana temiz bir şekilde yazdırıyoruz
        print("\n--- SİSTEM TAHMİN SONUCU ---")
        if tahmin_edilen_sinif == 'no_tumor':
            print(f"Bulgu: %{guven_orani:.2f} güven oranıyla TÜMÖR YOK (Sağlıklı).")
        else:
            print(f"Bulgu: %{guven_orani:.2f} güven oranıyla TÜMÖR TESPİT EDİLDİ.")
            print(f"Tümör Türü: {tahmin_edilen_sinif.capitalize()}")

    # Test klasörünün içinden rastgele bir Glioma tümörü resmi seçip sisteme veriyoruz:
    ornek_resim_yolu = '/content/brain_tumor_dataset/Testing/glioma/Te-gl_129.jpg'
    tumor_tahmini_yap(ornek_resim_yolu)

# Tümörlü bir resim test ediyoruz
ornek_resim_yolu = '/content/brain_tumor_dataset/Testing/glioma/Te-gl_344.jpg'

# Daha önce tanımladığımız fonksiyonu bu yeni resim için çalıştırıyoruz
tumor_tahmini_yap(ornek_resim_yolu)

# Tümörlü bir resim test ediyoruz
ornek_resim_yolu = '/content/brain_tumor_dataset/Testing/glioma/Te-gl_349.jpg'

# Daha önce tanımladığımız fonksiyonu bu yeni resim için çalıştırıyoruz
tumor_tahmini_yap(ornek_resim_yolu)